/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LawyersIndexRouteImport } from './routes/lawyers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LawyersLawyerIdRouteImport } from './routes/lawyers.$lawyerId'
import { Route as FirmsFirmIdRouteImport } from './routes/firms.$firmId'
import { Route as ApiLegalRouteImport } from './routes/api/legal'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminLawyersRouteImport } from './routes/admin.lawyers'
import { Route as AdminFirmsRouteImport } from './routes/admin.firms'
import { Route as AdminConsultationsRouteImport } from './routes/admin.consultations'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'
import { Route as AdminSubscriptionSubIdRouteImport } from './routes/admin.subscription.$subId'
import { Route as AdminStaffFormStaffIdRouteImport } from './routes/admin.staff-form.$staffId'
import { Route as AdminRoleFormRoleIdRouteImport } from './routes/admin.role-form.$roleId'
import { Route as AdminPlanFormPlanIdRouteImport } from './routes/admin.plan-form.$planId'
import { Route as AdminLawyerLawyerIdRouteImport } from './routes/admin.lawyer.$lawyerId'
import { Route as AdminLawyerAppAppIdRouteImport } from './routes/admin.lawyer-app.$appId'
import { Route as AdminInvoiceInvoiceIdRouteImport } from './routes/admin.invoice.$invoiceId'
import { Route as AdminFirmFirmIdRouteImport } from './routes/admin.firm.$firmId'
import { Route as AdminFirmAppAppIdRouteImport } from './routes/admin.firm-app.$appId'
import { Route as AdminConsultationConsultationIdRouteImport } from './routes/admin.consultation.$consultationId'
import { Route as AdminClientProfileClientIdRouteImport } from './routes/admin.client-profile.$clientId'
import { Route as AdminCaseCaseIdRouteImport } from './routes/admin.case.$caseId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyersIndexRoute = LawyersIndexRouteImport.update({
  id: '/lawyers/',
  path: '/lawyers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LawyersLawyerIdRoute = LawyersLawyerIdRouteImport.update({
  id: '/lawyers/$lawyerId',
  path: '/lawyers/$lawyerId',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsFirmIdRoute = FirmsFirmIdRouteImport.update({
  id: '/firms/$firmId',
  path: '/firms/$firmId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLegalRoute = ApiLegalRouteImport.update({
  id: '/api/legal',
  path: '/api/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLawyersRoute = AdminLawyersRouteImport.update({
  id: '/lawyers',
  path: '/lawyers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFirmsRoute = AdminFirmsRouteImport.update({
  id: '/firms',
  path: '/firms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultationsRoute = AdminConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionSubIdRoute = AdminSubscriptionSubIdRouteImport.update({
  id: '/subscription/$subId',
  path: '/subscription/$subId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffFormStaffIdRoute = AdminStaffFormStaffIdRouteImport.update({
  id: '/staff-form/$staffId',
  path: '/staff-form/$staffId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoleFormRoleIdRoute = AdminRoleFormRoleIdRouteImport.update({
  id: '/role-form/$roleId',
  path: '/role-form/$roleId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanFormPlanIdRoute = AdminPlanFormPlanIdRouteImport.update({
  id: '/plan-form/$planId',
  path: '/plan-form/$planId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLawyerLawyerIdRoute = AdminLawyerLawyerIdRouteImport.update({
  id: '/lawyer/$lawyerId',
  path: '/lawyer/$lawyerId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLawyerAppAppIdRoute = AdminLawyerAppAppIdRouteImport.update({
  id: '/lawyer-app/$appId',
  path: '/lawyer-app/$appId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoiceInvoiceIdRoute = AdminInvoiceInvoiceIdRouteImport.update({
  id: '/invoice/$invoiceId',
  path: '/invoice/$invoiceId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFirmFirmIdRoute = AdminFirmFirmIdRouteImport.update({
  id: '/firm/$firmId',
  path: '/firm/$firmId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFirmAppAppIdRoute = AdminFirmAppAppIdRouteImport.update({
  id: '/firm-app/$appId',
  path: '/firm-app/$appId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultationConsultationIdRoute =
  AdminConsultationConsultationIdRouteImport.update({
    id: '/consultation/$consultationId',
    path: '/consultation/$consultationId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminClientProfileClientIdRoute =
  AdminClientProfileClientIdRouteImport.update({
    id: '/client-profile/$clientId',
    path: '/client-profile/$clientId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCaseCaseIdRoute = AdminCaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/firms': typeof AdminFirmsRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/legal': typeof ApiLegalRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/lawyers/$lawyerId': typeof LawyersLawyerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/lawyers/': typeof LawyersIndexRoute
  '/admin/case/$caseId': typeof AdminCaseCaseIdRoute
  '/admin/client-profile/$clientId': typeof AdminClientProfileClientIdRoute
  '/admin/consultation/$consultationId': typeof AdminConsultationConsultationIdRoute
  '/admin/firm-app/$appId': typeof AdminFirmAppAppIdRoute
  '/admin/firm/$firmId': typeof AdminFirmFirmIdRoute
  '/admin/invoice/$invoiceId': typeof AdminInvoiceInvoiceIdRoute
  '/admin/lawyer-app/$appId': typeof AdminLawyerAppAppIdRoute
  '/admin/lawyer/$lawyerId': typeof AdminLawyerLawyerIdRoute
  '/admin/plan-form/$planId': typeof AdminPlanFormPlanIdRoute
  '/admin/role-form/$roleId': typeof AdminRoleFormRoleIdRoute
  '/admin/staff-form/$staffId': typeof AdminStaffFormStaffIdRoute
  '/admin/subscription/$subId': typeof AdminSubscriptionSubIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/firms': typeof AdminFirmsRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/legal': typeof ApiLegalRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/lawyers/$lawyerId': typeof LawyersLawyerIdRoute
  '/admin': typeof AdminIndexRoute
  '/lawyers': typeof LawyersIndexRoute
  '/admin/case/$caseId': typeof AdminCaseCaseIdRoute
  '/admin/client-profile/$clientId': typeof AdminClientProfileClientIdRoute
  '/admin/consultation/$consultationId': typeof AdminConsultationConsultationIdRoute
  '/admin/firm-app/$appId': typeof AdminFirmAppAppIdRoute
  '/admin/firm/$firmId': typeof AdminFirmFirmIdRoute
  '/admin/invoice/$invoiceId': typeof AdminInvoiceInvoiceIdRoute
  '/admin/lawyer-app/$appId': typeof AdminLawyerAppAppIdRoute
  '/admin/lawyer/$lawyerId': typeof AdminLawyerLawyerIdRoute
  '/admin/plan-form/$planId': typeof AdminPlanFormPlanIdRoute
  '/admin/role-form/$roleId': typeof AdminRoleFormRoleIdRoute
  '/admin/staff-form/$staffId': typeof AdminStaffFormStaffIdRoute
  '/admin/subscription/$subId': typeof AdminSubscriptionSubIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/firms': typeof AdminFirmsRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/legal': typeof ApiLegalRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/lawyers/$lawyerId': typeof LawyersLawyerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/lawyers/': typeof LawyersIndexRoute
  '/admin/case/$caseId': typeof AdminCaseCaseIdRoute
  '/admin/client-profile/$clientId': typeof AdminClientProfileClientIdRoute
  '/admin/consultation/$consultationId': typeof AdminConsultationConsultationIdRoute
  '/admin/firm-app/$appId': typeof AdminFirmAppAppIdRoute
  '/admin/firm/$firmId': typeof AdminFirmFirmIdRoute
  '/admin/invoice/$invoiceId': typeof AdminInvoiceInvoiceIdRoute
  '/admin/lawyer-app/$appId': typeof AdminLawyerAppAppIdRoute
  '/admin/lawyer/$lawyerId': typeof AdminLawyerLawyerIdRoute
  '/admin/plan-form/$planId': typeof AdminPlanFormPlanIdRoute
  '/admin/role-form/$roleId': typeof AdminRoleFormRoleIdRoute
  '/admin/staff-form/$staffId': typeof AdminStaffFormStaffIdRoute
  '/admin/subscription/$subId': typeof AdminSubscriptionSubIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/ai'
    | '/cases'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/templates'
    | '/admin/cases'
    | '/admin/clients'
    | '/admin/consultations'
    | '/admin/firms'
    | '/admin/lawyers'
    | '/admin/plans'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/api/chat'
    | '/api/legal'
    | '/firms/$firmId'
    | '/lawyers/$lawyerId'
    | '/admin/'
    | '/lawyers/'
    | '/admin/case/$caseId'
    | '/admin/client-profile/$clientId'
    | '/admin/consultation/$consultationId'
    | '/admin/firm-app/$appId'
    | '/admin/firm/$firmId'
    | '/admin/invoice/$invoiceId'
    | '/admin/lawyer-app/$appId'
    | '/admin/lawyer/$lawyerId'
    | '/admin/plan-form/$planId'
    | '/admin/role-form/$roleId'
    | '/admin/staff-form/$staffId'
    | '/admin/subscription/$subId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ai'
    | '/cases'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/templates'
    | '/admin/cases'
    | '/admin/clients'
    | '/admin/consultations'
    | '/admin/firms'
    | '/admin/lawyers'
    | '/admin/plans'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/api/chat'
    | '/api/legal'
    | '/firms/$firmId'
    | '/lawyers/$lawyerId'
    | '/admin'
    | '/lawyers'
    | '/admin/case/$caseId'
    | '/admin/client-profile/$clientId'
    | '/admin/consultation/$consultationId'
    | '/admin/firm-app/$appId'
    | '/admin/firm/$firmId'
    | '/admin/invoice/$invoiceId'
    | '/admin/lawyer-app/$appId'
    | '/admin/lawyer/$lawyerId'
    | '/admin/plan-form/$planId'
    | '/admin/role-form/$roleId'
    | '/admin/staff-form/$staffId'
    | '/admin/subscription/$subId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/ai'
    | '/cases'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/templates'
    | '/admin/cases'
    | '/admin/clients'
    | '/admin/consultations'
    | '/admin/firms'
    | '/admin/lawyers'
    | '/admin/plans'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/api/chat'
    | '/api/legal'
    | '/firms/$firmId'
    | '/lawyers/$lawyerId'
    | '/admin/'
    | '/lawyers/'
    | '/admin/case/$caseId'
    | '/admin/client-profile/$clientId'
    | '/admin/consultation/$consultationId'
    | '/admin/firm-app/$appId'
    | '/admin/firm/$firmId'
    | '/admin/invoice/$invoiceId'
    | '/admin/lawyer-app/$appId'
    | '/admin/lawyer/$lawyerId'
    | '/admin/plan-form/$planId'
    | '/admin/role-form/$roleId'
    | '/admin/staff-form/$staffId'
    | '/admin/subscription/$subId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRoute
  CasesRoute: typeof CasesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplatesRoute: typeof TemplatesRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiLegalRoute: typeof ApiLegalRoute
  FirmsFirmIdRoute: typeof FirmsFirmIdRoute
  LawyersLawyerIdRoute: typeof LawyersLawyerIdRoute
  LawyersIndexRoute: typeof LawyersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyers/': {
      id: '/lawyers/'
      path: '/lawyers'
      fullPath: '/lawyers/'
      preLoaderRoute: typeof LawyersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lawyers/$lawyerId': {
      id: '/lawyers/$lawyerId'
      path: '/lawyers/$lawyerId'
      fullPath: '/lawyers/$lawyerId'
      preLoaderRoute: typeof LawyersLawyerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms/$firmId': {
      id: '/firms/$firmId'
      path: '/firms/$firmId'
      fullPath: '/firms/$firmId'
      preLoaderRoute: typeof FirmsFirmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/legal': {
      id: '/api/legal'
      path: '/api/legal'
      fullPath: '/api/legal'
      preLoaderRoute: typeof ApiLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lawyers': {
      id: '/admin/lawyers'
      path: '/lawyers'
      fullPath: '/admin/lawyers'
      preLoaderRoute: typeof AdminLawyersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/firms': {
      id: '/admin/firms'
      path: '/firms'
      fullPath: '/admin/firms'
      preLoaderRoute: typeof AdminFirmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultations': {
      id: '/admin/consultations'
      path: '/consultations'
      fullPath: '/admin/consultations'
      preLoaderRoute: typeof AdminConsultationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscription/$subId': {
      id: '/admin/subscription/$subId'
      path: '/subscription/$subId'
      fullPath: '/admin/subscription/$subId'
      preLoaderRoute: typeof AdminSubscriptionSubIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff-form/$staffId': {
      id: '/admin/staff-form/$staffId'
      path: '/staff-form/$staffId'
      fullPath: '/admin/staff-form/$staffId'
      preLoaderRoute: typeof AdminStaffFormStaffIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/role-form/$roleId': {
      id: '/admin/role-form/$roleId'
      path: '/role-form/$roleId'
      fullPath: '/admin/role-form/$roleId'
      preLoaderRoute: typeof AdminRoleFormRoleIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plan-form/$planId': {
      id: '/admin/plan-form/$planId'
      path: '/plan-form/$planId'
      fullPath: '/admin/plan-form/$planId'
      preLoaderRoute: typeof AdminPlanFormPlanIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lawyer/$lawyerId': {
      id: '/admin/lawyer/$lawyerId'
      path: '/lawyer/$lawyerId'
      fullPath: '/admin/lawyer/$lawyerId'
      preLoaderRoute: typeof AdminLawyerLawyerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lawyer-app/$appId': {
      id: '/admin/lawyer-app/$appId'
      path: '/lawyer-app/$appId'
      fullPath: '/admin/lawyer-app/$appId'
      preLoaderRoute: typeof AdminLawyerAppAppIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoice/$invoiceId': {
      id: '/admin/invoice/$invoiceId'
      path: '/invoice/$invoiceId'
      fullPath: '/admin/invoice/$invoiceId'
      preLoaderRoute: typeof AdminInvoiceInvoiceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/firm/$firmId': {
      id: '/admin/firm/$firmId'
      path: '/firm/$firmId'
      fullPath: '/admin/firm/$firmId'
      preLoaderRoute: typeof AdminFirmFirmIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/firm-app/$appId': {
      id: '/admin/firm-app/$appId'
      path: '/firm-app/$appId'
      fullPath: '/admin/firm-app/$appId'
      preLoaderRoute: typeof AdminFirmAppAppIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultation/$consultationId': {
      id: '/admin/consultation/$consultationId'
      path: '/consultation/$consultationId'
      fullPath: '/admin/consultation/$consultationId'
      preLoaderRoute: typeof AdminConsultationConsultationIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/client-profile/$clientId': {
      id: '/admin/client-profile/$clientId'
      path: '/client-profile/$clientId'
      fullPath: '/admin/client-profile/$clientId'
      preLoaderRoute: typeof AdminClientProfileClientIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/case/$caseId': {
      id: '/admin/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/admin/case/$caseId'
      preLoaderRoute: typeof AdminCaseCaseIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCasesRoute: typeof AdminCasesRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminConsultationsRoute: typeof AdminConsultationsRoute
  AdminFirmsRoute: typeof AdminFirmsRoute
  AdminLawyersRoute: typeof AdminLawyersRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCaseCaseIdRoute: typeof AdminCaseCaseIdRoute
  AdminClientProfileClientIdRoute: typeof AdminClientProfileClientIdRoute
  AdminConsultationConsultationIdRoute: typeof AdminConsultationConsultationIdRoute
  AdminFirmAppAppIdRoute: typeof AdminFirmAppAppIdRoute
  AdminFirmFirmIdRoute: typeof AdminFirmFirmIdRoute
  AdminInvoiceInvoiceIdRoute: typeof AdminInvoiceInvoiceIdRoute
  AdminLawyerAppAppIdRoute: typeof AdminLawyerAppAppIdRoute
  AdminLawyerLawyerIdRoute: typeof AdminLawyerLawyerIdRoute
  AdminPlanFormPlanIdRoute: typeof AdminPlanFormPlanIdRoute
  AdminRoleFormRoleIdRoute: typeof AdminRoleFormRoleIdRoute
  AdminStaffFormStaffIdRoute: typeof AdminStaffFormStaffIdRoute
  AdminSubscriptionSubIdRoute: typeof AdminSubscriptionSubIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCasesRoute: AdminCasesRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminConsultationsRoute: AdminConsultationsRoute,
  AdminFirmsRoute: AdminFirmsRoute,
  AdminLawyersRoute: AdminLawyersRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCaseCaseIdRoute: AdminCaseCaseIdRoute,
  AdminClientProfileClientIdRoute: AdminClientProfileClientIdRoute,
  AdminConsultationConsultationIdRoute: AdminConsultationConsultationIdRoute,
  AdminFirmAppAppIdRoute: AdminFirmAppAppIdRoute,
  AdminFirmFirmIdRoute: AdminFirmFirmIdRoute,
  AdminInvoiceInvoiceIdRoute: AdminInvoiceInvoiceIdRoute,
  AdminLawyerAppAppIdRoute: AdminLawyerAppAppIdRoute,
  AdminLawyerLawyerIdRoute: AdminLawyerLawyerIdRoute,
  AdminPlanFormPlanIdRoute: AdminPlanFormPlanIdRoute,
  AdminRoleFormRoleIdRoute: AdminRoleFormRoleIdRoute,
  AdminStaffFormStaffIdRoute: AdminStaffFormStaffIdRoute,
  AdminSubscriptionSubIdRoute: AdminSubscriptionSubIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRoute,
  CasesRoute: CasesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplatesRoute: TemplatesRoute,
  ApiChatRoute: ApiChatRoute,
  ApiLegalRoute: ApiLegalRoute,
  FirmsFirmIdRoute: FirmsFirmIdRoute,
  LawyersLawyerIdRoute: LawyersLawyerIdRoute,
  LawyersIndexRoute: LawyersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
