/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LawyersIndexRouteImport } from './routes/lawyers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LawyersLawyerIdRouteImport } from './routes/lawyers.$lawyerId'
import { Route as FirmsFirmIdRouteImport } from './routes/firms.$firmId'
import { Route as ApiLegalRouteImport } from './routes/api/legal'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminLawyersRouteImport } from './routes/admin.lawyers'
import { Route as AdminFirmsRouteImport } from './routes/admin.firms'
import { Route as AdminConsultationsRouteImport } from './routes/admin.consultations'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyersIndexRoute = LawyersIndexRouteImport.update({
  id: '/lawyers/',
  path: '/lawyers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LawyersLawyerIdRoute = LawyersLawyerIdRouteImport.update({
  id: '/lawyers/$lawyerId',
  path: '/lawyers/$lawyerId',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsFirmIdRoute = FirmsFirmIdRouteImport.update({
  id: '/firms/$firmId',
  path: '/firms/$firmId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLegalRoute = ApiLegalRouteImport.update({
  id: '/api/legal',
  path: '/api/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLawyersRoute = AdminLawyersRouteImport.update({
  id: '/lawyers',
  path: '/lawyers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFirmsRoute = AdminFirmsRouteImport.update({
  id: '/firms',
  path: '/firms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultationsRoute = AdminConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/firms': typeof AdminFirmsRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/legal': typeof ApiLegalRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/lawyers/$lawyerId': typeof LawyersLawyerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/lawyers/': typeof LawyersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/firms': typeof AdminFirmsRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/legal': typeof ApiLegalRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/lawyers/$lawyerId': typeof LawyersLawyerIdRoute
  '/admin': typeof AdminIndexRoute
  '/lawyers': typeof LawyersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/firms': typeof AdminFirmsRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/legal': typeof ApiLegalRoute
  '/firms/$firmId': typeof FirmsFirmIdRoute
  '/lawyers/$lawyerId': typeof LawyersLawyerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/lawyers/': typeof LawyersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/ai'
    | '/cases'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/templates'
    | '/admin/cases'
    | '/admin/clients'
    | '/admin/consultations'
    | '/admin/firms'
    | '/admin/lawyers'
    | '/admin/plans'
    | '/admin/subscriptions'
    | '/api/chat'
    | '/api/legal'
    | '/firms/$firmId'
    | '/lawyers/$lawyerId'
    | '/admin/'
    | '/lawyers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ai'
    | '/cases'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/templates'
    | '/admin/cases'
    | '/admin/clients'
    | '/admin/consultations'
    | '/admin/firms'
    | '/admin/lawyers'
    | '/admin/plans'
    | '/admin/subscriptions'
    | '/api/chat'
    | '/api/legal'
    | '/firms/$firmId'
    | '/lawyers/$lawyerId'
    | '/admin'
    | '/lawyers'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/ai'
    | '/cases'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/templates'
    | '/admin/cases'
    | '/admin/clients'
    | '/admin/consultations'
    | '/admin/firms'
    | '/admin/lawyers'
    | '/admin/plans'
    | '/admin/subscriptions'
    | '/api/chat'
    | '/api/legal'
    | '/firms/$firmId'
    | '/lawyers/$lawyerId'
    | '/admin/'
    | '/lawyers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRoute
  CasesRoute: typeof CasesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplatesRoute: typeof TemplatesRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiLegalRoute: typeof ApiLegalRoute
  FirmsFirmIdRoute: typeof FirmsFirmIdRoute
  LawyersLawyerIdRoute: typeof LawyersLawyerIdRoute
  LawyersIndexRoute: typeof LawyersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyers/': {
      id: '/lawyers/'
      path: '/lawyers'
      fullPath: '/lawyers/'
      preLoaderRoute: typeof LawyersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lawyers/$lawyerId': {
      id: '/lawyers/$lawyerId'
      path: '/lawyers/$lawyerId'
      fullPath: '/lawyers/$lawyerId'
      preLoaderRoute: typeof LawyersLawyerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms/$firmId': {
      id: '/firms/$firmId'
      path: '/firms/$firmId'
      fullPath: '/firms/$firmId'
      preLoaderRoute: typeof FirmsFirmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/legal': {
      id: '/api/legal'
      path: '/api/legal'
      fullPath: '/api/legal'
      preLoaderRoute: typeof ApiLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lawyers': {
      id: '/admin/lawyers'
      path: '/lawyers'
      fullPath: '/admin/lawyers'
      preLoaderRoute: typeof AdminLawyersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/firms': {
      id: '/admin/firms'
      path: '/firms'
      fullPath: '/admin/firms'
      preLoaderRoute: typeof AdminFirmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultations': {
      id: '/admin/consultations'
      path: '/consultations'
      fullPath: '/admin/consultations'
      preLoaderRoute: typeof AdminConsultationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCasesRoute: typeof AdminCasesRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminConsultationsRoute: typeof AdminConsultationsRoute
  AdminFirmsRoute: typeof AdminFirmsRoute
  AdminLawyersRoute: typeof AdminLawyersRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCasesRoute: AdminCasesRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminConsultationsRoute: AdminConsultationsRoute,
  AdminFirmsRoute: AdminFirmsRoute,
  AdminLawyersRoute: AdminLawyersRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRoute,
  CasesRoute: CasesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplatesRoute: TemplatesRoute,
  ApiChatRoute: ApiChatRoute,
  ApiLegalRoute: ApiLegalRoute,
  FirmsFirmIdRoute: FirmsFirmIdRoute,
  LawyersLawyerIdRoute: LawyersLawyerIdRoute,
  LawyersIndexRoute: LawyersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
